import React from "react";

import Pixel from "./Pixel";

const App = () => {
  return (
    <>
      <div>Kaleidoscope</div>
      <div></div>
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
    </>
  );
};

export default App;
